easy_admin:
    entities:
        User:
            label: User
            class: AppBundle\Entity\User
            edit:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email', label: 'E-mail address' }
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'surname' }
                    - { property: 'name' }
                    - { property: 'county' }
                    - { property: 'city' }
                    - { property: 'address' }
                    - { property: 'phone' }
                    - { property: 'enabled'}
                    - { property: 'locked'}
            new:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email', label: 'E-mail address' }
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'surname' }
                    - { property: 'name' }
                    - { property: 'county' }
                    - { property: 'city' }
                    - { property: 'address' }
                    - { property: 'phone' }
                    - { property: 'enabled'}
                    - { property: 'locked'}
        Group:
            label: Group
            class: AppBundle\Entity\Group
            list:
                fields:
                    - { property: name }
                    - { property: description }
                    - { property: country }
                    - { property: city }
                    - { property: yearFoundation }
            show:
                fields:
                    - { property: name }
                    - { property: description }
                    - { property: country }
                    - { property: city }
                    - { property: yearFoundation }
            new:
                fields:
                    - { property: name }
                    - { property: description }
                    - { property: country }
                    - { property: city }
                    - { property: yearFoundation }
            edit:
                fields:
                    - { property: name }
                    - { property: description }
                    - { property: country }
                    - { property: city }
                    - { property: yearFoundation }
        Genre:
            label: Genre
            class: AppBundle\Entity\Genre

