easy_admin:
    entities:
        User:
            label: User
            class: AppBundle\Entity\User
            edit:
                fields: ['username', 'email', 'enabled', 'locked']
            new:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email', label: 'E-mail address' }
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'surname' }
                    - { property: 'name' }
                    - { property: 'county' }
                    - { property: 'city' }
                    - { property: 'address' }
                    - { property: 'phone' }
                    - { property: 'enabled'}
                    - { property: 'locked'}
                    - { property: 'createdAt', label: 'Created At' }
                    - { property: 'updatedAt', label: 'Updated At' }
