old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        send_message:
            connection:       default
            exchange_options: {name: 'send_message', type: direct}
    consumers:
        send_message:
            connection:       default
            exchange_options: {name: 'send_message', type: direct}
            queue_options:    {name: 'send_message'}
            callback:         app.message
