services:
    app.event:
        class: AppBundle\Service\EventService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.group:
        class: AppBundle\Service\GroupService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.group_api:
        class: AppBundle\Service\GroupApiService
        arguments:
            - '%last_fm_api_url%'
            - '%last_fm_key%'

    app.manager:
        class: AppBundle\Service\ManagerService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.message:
        class:      AppBundle\Service\MessageService
        arguments:
            - @mailer
            - '%swiftmailer.mailer.default.transport.smtp.username%'

    app.user:
        class: AppBundle\Service\UserService
        arguments:
            - @doctrine.orm.default_entity_manager

    app.vich_uploader_directory_namer:
        class: AppBundle\Service\DirectoryNamerService

    my_user_provider:
        class: AppBundle\Security\Provider\OAuthUserProvider
        arguments:
            - "@fos_user.user_manager"
            - { facebook: facebookId, google: googleId, vk: vkId }
